### ISSUE TITLE
No development?

### ISSUE THREAD

**Issue by cupnoodle** [turbobabr/sketch-barcode#1]
I was excited when I found this on Google but after I clicked it in this repository is empty  😭

**Comment by turbobabr** [comment]
I have this plugin but it's not published. It was built for Sketch 3.0 about two years ago. What kind of barcode do you need to bring to sketch?

You can easily generate any type of barcode, using this online tool, then save it as SVG and import into sketch document:
http://www.barcode-generator.org/

**Comment by cupnoodle** [comment]
I see, I have generated the barcode using the link you gave just now, thanks! I think it will be really handy if I can just generate barcode in sketch in vector form. Thanks for the prompt reply!
